// <auto-generated />
using System;
using KolokwiumZawody.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KolokwiumZawody.Migrations
{
    [DbContext(typeof(ChampionshipDbContext))]
    partial class ChampionshipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KolokwiumZawody.Models.Championship", b =>
                {
                    b.Property<int>("IdChampionship")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("IdChampionship");

                    b.ToTable("Championships");

                    b.HasData(
                        new
                        {
                            IdChampionship = 1,
                            OfficialName = "pilka",
                            Year = 1990
                        },
                        new
                        {
                            IdChampionship = 2,
                            OfficialName = "siatkowka",
                            Year = 1994
                        });
                });

            modelBuilder.Entity("KolokwiumZawody.Models.ChampionshipTeam", b =>
                {
                    b.Property<int>("IdTeam")
                        .HasColumnType("int");

                    b.Property<int>("IdChampionship")
                        .HasColumnType("int");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasKey("IdTeam", "IdChampionship");

                    b.HasIndex("IdChampionship");

                    b.ToTable("ChampionshipTeams");

                    b.HasData(
                        new
                        {
                            IdTeam = 1,
                            IdChampionship = 1,
                            Score = 70f
                        },
                        new
                        {
                            IdTeam = 2,
                            IdChampionship = 1,
                            Score = 60f
                        },
                        new
                        {
                            IdTeam = 2,
                            IdChampionship = 2,
                            Score = 40f
                        });
                });

            modelBuilder.Entity("KolokwiumZawody.Models.Player", b =>
                {
                    b.Property<int>("IdPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdPlayer");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("KolokwiumZawody.Models.PlayerTeam", b =>
                {
                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<int>("IdTeam")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<int>("NumOnShirt")
                        .HasColumnType("int");

                    b.HasKey("IdPlayer", "IdTeam");

                    b.HasIndex("IdTeam");

                    b.ToTable("PlayerTeams");
                });

            modelBuilder.Entity("KolokwiumZawody.Models.Team", b =>
                {
                    b.Property<int>("IdTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("IdTeam");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            IdTeam = 1,
                            MaxAge = 12,
                            TeamName = "Misie"
                        },
                        new
                        {
                            IdTeam = 2,
                            MaxAge = 15,
                            TeamName = "Ptysie"
                        },
                        new
                        {
                            IdTeam = 3,
                            MaxAge = 18,
                            TeamName = "Rysie"
                        });
                });

            modelBuilder.Entity("KolokwiumZawody.Models.ChampionshipTeam", b =>
                {
                    b.HasOne("KolokwiumZawody.Models.Championship", "Championship")
                        .WithMany("ChampionshipTeams")
                        .HasForeignKey("IdChampionship")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KolokwiumZawody.Models.Team", "Team")
                        .WithMany("ChampionshipTeams")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KolokwiumZawody.Models.PlayerTeam", b =>
                {
                    b.HasOne("KolokwiumZawody.Models.Player", "Player")
                        .WithMany("PlayerTeams")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KolokwiumZawody.Models.Team", "Team")
                        .WithMany("PlayerTeams")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
